name: 'Custom steps to run before R packages are installed'

runs:
  using: "composite"
  steps:
    - name: Define R CMD check error condition
      run: |
        echo '_R_CHECK_PKG_SIZES_=FALSE' | tee -a $GITHUB_ENV
      shell: bash

    - name: Compute cache key
      run: |
        echo "DUCKDB_R_PREBUILT_ARCHIVE_GHA_CACHE_KEY=duckdb-${{ runner.os }}-$($(R CMD config CXX) --version | head -n 1 | sed -r 's/[, ]/-/g')-${{ hashFiles('src/duckdb/**') }}-2" | tee -a $GITHUB_ENV
        echo "DUCKDB_R_PREBUILT_ARCHIVE=${HOME}/duckdb.a" | tee -a $GITHUB_ENV
      shell: bash

    - name: Cache duckdb archive
      uses: actions/cache@v3
      with:
        lookup-only: true
        path: ${{ env.DUCKDB_R_PREBUILT_ARCHIVE }}
        key: ${{ env.DUCKDB_R_PREBUILT_ARCHIVE_GHA_CACHE_KEY }}
