# Generated by rconfigure.py, do not edit by hand
# DuckDB version information

duckdb_version <- "1.5.0-dev7669"

# Function to get DuckDB version without establishing a connection
get_duckdb_version <- function() {
  duckdb_version
}
